import smtplib
from email.mime.text import MIMEText
import os
from dotenv import load_dotenv
from app.services.gemini_service import generate_email_content

# Load environment variables for email credentials
load_dotenv()

def send_test_email(recipient_email: str, candidate_name: str, job_title: str, test_id: str):
    """
    Sends a professional email with a unique test link, with content generated by Gemini AI.
    
    Args:
        recipient_email (str): The email address of the candidate.
        candidate_name (str): The name of the candidate.
        job_title (str): The job title for which the test was created.
        test_id (str): The unique ID of the test in Firestore.
    """
    smtp_server = "smtp.gmail.com"
    smtp_port = 587
    sender_email = os.getenv("SENDER_EMAIL")
    sender_password = os.getenv("SENDER_PASSWORD")

    if not sender_email or not sender_password:
        print("❌ Email credentials are not set. Please add SENDER_EMAIL and SENDER_PASSWORD to your .env file.")
        return False

    # Construct the unique test URL
    test_link = f"http://localhost:5173/take-test/{test_id}"

    # Generate the professional email content using Gemini AI
    body = generate_email_content(candidate_name, test_link, job_title)

    # Extract the subject from the AI-generated body (it's the first line)
    subject_line = "Aptitude Test" # Fallback subject
    body_lines = body.strip().split("\n")
    if body_lines[0].lower().startswith("subject:"):
        subject_line = body_lines.pop(0).replace("Subject:", "").strip()
    else:
        # If the AI didn't format it with "Subject:", look for the first non-empty line
        subject_line = body_lines[0].strip() if body_lines else subject_line
        
    final_body = "\n".join(body_lines).strip()
    
    msg = MIMEText(final_body)
    msg['Subject'] = subject_line
    msg['From'] = sender_email
    msg['To'] = recipient_email

    try:
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()  # Secure the connection
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, recipient_email, msg.as_string())
        print(f"✅ Email sent to {recipient_email} with test ID: {test_id}")
        return True
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        return False
